#!/bin/sh

uci set luci.main.lang=zh_cn
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

# Network Set
uci set network.lan.ipaddr='192.168.8.1'
uci set network.lan.netmask='255.255.252.0'
uci set network.lan.ifname='eth0 eth1 eth2'
uci set network.lan.broadcast='192.168.11.255'
uci set network.wan.ifname='eth5'
uci set network.wan.proto='pppoe'
uci set network.wan6.ifname='eth5'
uci set network.2wan=interface
uci set network.2wan.ifname='eth4'
uci set network.2wan.proto='pppoe'
uci set network.2wan6.ifname='eth4'
uci commit network

uci set firewall.@zone[1].forward='ACCEPT'
uci commit firewall

uci set dhcp.lan.start='2'
uci set dhcp.lan.limit='254'
uci commit dhcp

uci set arpbind.@arpbind[0]=arpbind
uci set arpbind.@arpbind[0].ifname='br-lan'
uci set arpbind.@arpbind[0].ipaddr='192.168.8.2'
uci set arpbind.@arpbind[0].macaddr='a8:a1:59:26:f8:d3'
uci set arpbind.@arpbind[1]=arpbind
uci set arpbind.@arpbind[1].ifname='br-lan'
uci set arpbind.@arpbind[1].ipaddr='192.168.8.3'
uci set arpbind.@arpbind[1].macaddr='00:11:32:5d:97:0c'
uci commit arpbind

uci set uhttpd.defaults.commonname='GWRT'
uci commit uhttpd

#uci set
#uci set
#uci set
#uci set
#uci set
#uci set
#uci set
#uci set
#uci set
#uci set
#uci set
#uci set



#rm -f /usr/lib/lua/luci/view/admin_status/index/mwan.htm
#rm -f /usr/lib/lua/luci/view/admin_status/index/upnp.htm
#rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
#rm -f /usr/lib/lua/luci/view/admin_status/index/minidlna.htm

#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/aria2.lua
#sed -i 's/services/nas/g' /usr/lib/lua/luci/view/aria2/overview_status.htm
#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/hd_idle.lua
#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba.lua
#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/minidlna.lua
#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/transmission.lua
#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/mjpg-streamer.lua
#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/p910nd.lua
#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/usb_printer.lua
#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/xunlei.lua
#sed -i 's/services/nas/g'  /usr/lib/lua/luci/view/minidlna_status.htm

ln -sf /sbin/ip /usr/bin/ip

#sed -i 's#downloads.openwrt.org#mirrors.cloud.tencent.com/lede#g' /etc/opkg/distfeeds.conf
#echo '' >> /etc/opkg/distfeeds.conf
echo 'src/gz yun_core https://yun.guyezi.com/lede/v21.02.0-rc3/targets/x86/64/packages' >> /etc/opkg/distfeeds.conf
echo 'src/gz yun_base https://yun.guyezi.com/lede/v21.02.0-rc3/packages/x86_64/base' >> /etc/opkg/distfeeds.conf
echo 'src/gz yun_helloworld https://yun.guyezi.com/lede/v21.02.0-rc3/packages/x86_64/helloworld' >> /etc/opkg/distfeeds.conf
echo 'src/gz yun_luci https://yun.guyezi.com/lede/v21.02.0-rc3/packages/x86_64/luci' >> /etc/opkg/distfeeds.conf
echo 'src/gz yun_packages https://yun.guyezi.com/lede/v21.02.0-rc3/packages/x86_64/packages' >> /etc/opkg/distfeeds.conf
echo 'src/gz yun_routing https://yun.guyezi.com/lede/v21.02.0-rc3/packages/x86_64/routing' >> /etc/opkg/distfeeds.conf
echo 'src/gz yun_slplay https://yun.guyezi.com/lede/v21.02.0-rc3/packages/x86_64/slplay' >> /etc/opkg/distfeeds.conf
echo 'src/gz yun_telephony https://yun.guyezi.com/lede/v21.02.0-rc3/packages/x86_64/telephony' >> /etc/opkg/distfeeds.conf
sed -i 's/root::0:0:99999:7:::/root:$1$UMiavMXh$lailtBi3b8.5w4ouiyyeI.:0:0:99999:7:::/g' /etc/shadow
echo 'guyezi:$1$UMiavMXh$lailtBi3b8.5w4ouiyyeI.:0:0:99999:7:::' >> /etc/shadow
echo 'guyezi:x:0:0:root:/root:/bin/ash' >> /etc/passwd

#sed -i "s/# //g" /etc/opkg/distfeeds.conf
#sed -i '/openwrt_luci/ { s/snapshots/releases\/18.06.9/g; }'  /etc/opkg/distfeeds.conf

sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
echo 'iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
echo 'iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
echo '[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
echo '[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh

#sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
#echo "DISTRIB_REVISION='R21.7.26'" >> /etc/openwrt_release
#sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
#echo "DISTRIB_DESCRIPTION='OpenWrt '" >> /etc/openwrt_release

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

echo 'hsts=0' > /root/.wgetrc

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
